name: Linter and Typescript check

on:
    push:
        branches: [master, add-ci-cd]
    # pull_request:
    #     types: [opened, reopened]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: ESLint check
              run: npx eslint "./src/**/*.{ts,tsx}" --config .eslintrc.js

    tsc:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'
            - name: Install Dependencies
              run: npm ci
            - name: TypeScript Check
              run: npx tsc
