name: Deploy dev

on:
    push:
        branches: [master, add-ci-cd]
jobs:
    publish:
        runs-on: ubuntu-latest
        needs: [build_and_publish]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install OpenVPN
              run: |
                  sudo apt-get update
                  sudo apt-get --assume-yes --no-install-recommends install openvpn

            - name: Setup VPN config
              run: |
                  echo "${{ secrets.CA_CRT }}" > ca.crt
                  echo "${{ secrets.SECRET_USERNAME_PASSWORD }}" > secret.txt
                  echo "${{ secrets.TLS_KEY }}" > tls.key          
                  echo "${{ secrets.CONFIG }}" > config.ovpn

            - name: Connect VPN
              run: sudo openvpn --config "config.ovpn" --log "vpn.log" --daemon

            - name: Wait for a VPN connection
              timeout-minutes: 1
              run: until ping -c1 ${{ secrets.TEST_HOST_IP }}; do sleep 2; done

            - name: 'Run deploy on server'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.TEST_HOST_IP }}
                  username: ${{ secrets.TEST_SERVER_USERNAME }}
                  password: ${{ secrets.TEST_SERVER_PASSWORD }}
                  script: |
                      cd client-app/LK
                      echo ${{ secrets.TEST_SERVER_PASSWORD }} | sudo -S docker compose -p web pull
                      echo ${{ secrets.TEST_SERVER_PASSWORD }} | sudo -S docker compose -p web up -d
            - name: Kill VPN connection
              if: always()
              run: |
                  sudo chmod 777 vpn.log
                  sudo killall openvpn

            - name: Upload VPN logs
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: VPN logs
                  path: vpn.log
