name: Docker Image CI for GHCR

on:
    push:
        branches: [master, add-ci-cd]

    workflow_run:
        workflows: ['checks.yml']
        types:
            - completed

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build and publish
              run: |
                  docker login --username skaele --password ${{ secrets.GH_PAT }} ghcr.io
                  docker build . --tag ghcr.io/skaele/mospolytech-lk-ghcr:latest
                  docker push ghcr.io/skaele/mospolytech-lk-ghcr:latest
